apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    name: default-addresspool
    namespace: metallb-system
  spec:
    addresses:
    - 200.221.2.xxx-200.221.2.xxx
    - 192.168.10.10-192.168.10.100
    autoAssign: true
kind: List
