apiVersion: v1
kind: Service
metadata:
  name: pg-cluster-lb-external-1
  namespace: corcelli
  annotations:
    # Para provedores de nuvem específicos (opcional, dependendo do ambiente)
    #service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    postgres-operator.crunchydata.com/cluster: pg-corcelli  # Nome do cluster PostgreSQL
    postgres-operator.crunchydata.com/role: master
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432  # Porta externa do LoadBalancer
      targetPort: 5432  # Porta do PostgreSQL no container
